<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PlanCuentasSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * Plan de cuentas contables para negocio de empeños/créditos prendarios
     */
    public function run(): void
    {
        $cuentas = $this->obtenerPlanCuentas();

        foreach ($cuentas as $cuenta) {
            // Buscar el ID del padre si existe
            if (!empty($cuenta['codigo_padre'])) {
                $padre = DB::table('ctb_nomenclatura')
                    ->where('codigo_cuenta', $cuenta['codigo_padre'])
                    ->first();

                $cuenta['cuenta_padre_id'] = $padre ? $padre->id : null;
            }

            unset($cuenta['codigo_padre']);

            DB::table('ctb_nomenclatura')->updateOrInsert(
                ['codigo_cuenta' => $cuenta['codigo_cuenta']],
                array_merge($cuenta, [
                    'created_at' => now(),
                    'updated_at' => now(),
                ])
            );
        }

        $this->command->info('✓ Plan de cuentas creado exitosamente');
    }

    private function obtenerPlanCuentas(): array
    {
        return [
            // ==================== ACTIVOS ====================
            [
                'codigo_cuenta' => '1',
                'nombre_cuenta' => 'ACTIVO',
                'tipo' => 'activo',
                'naturaleza' => 'deudora',
                'nivel' => 1,
                'codigo_padre' => null,
                'acepta_movimientos' => false,
                'requiere_auxiliar' => false,
                'categoria_flujo' => 'ninguno',
                'estado' => true,
            ],
            [
                'codigo_cuenta' => '1101',
                'nombre_cuenta' => 'ACTIVO CORRIENTE',
                'tipo' => 'activo',
                'naturaleza' => 'deudora',
                'nivel' => 2,
                'codigo_padre' => '1',
                'acepta_movimientos' => false,
                'requiere_auxiliar' => false,
                'categoria_flujo' => 'ninguno',
                'estado' => true,
            ],

            // Caja y Bancos
            [
                'codigo_cuenta' => '1101.01',
                'nombre_cuenta' => 'Caja y Bancos',
                'tipo' => 'activo',
                'naturaleza' => 'deudora',
                'nivel' => 3,
                'codigo_padre' => '1101',
                'acepta_movimientos' => false,
                'requiere_auxiliar' => false,
                'categoria_flujo' => 'operacion',
                'estado' => true,
            ],
            [
                'codigo_cuenta' => '1101.01.001',
                'nombre_cuenta' => 'Caja General',
                'tipo' => 'activo',
                'naturaleza' => 'deudora',
                'nivel' => 4,
                'codigo_padre' => '1101.01',
                'acepta_movimientos' => true,
                'requiere_auxiliar' => false,
                'categoria_flujo' => 'operacion',
                'estado' => true,
            ],
            [
                'codigo_cuenta' => '1101.01.002',
                'nombre_cuenta' => 'Caja Chica',
                'tipo' => 'activo',
                'naturaleza' => 'deudora',
                'nivel' => 4,
                'codigo_padre' => '1101.01',
                'acepta_movimientos' => true,
                'requiere_auxiliar' => false,
                'categoria_flujo' => 'operacion',
                'estado' => true,
            ],
            [
                'codigo_cuenta' => '1101.01.003',
                'nombre_cuenta' => 'Bancos',
                'tipo' => 'activo',
                'naturaleza' => 'deudora',
                'nivel' => 4,
                'codigo_padre' => '1101.01',
                'acepta_movimientos' => true,
                'requiere_auxiliar' => false,
                'categoria_flujo' => 'operacion',
                'estado' => true,
            ],

            // Créditos por Cobrar
            [
                'codigo_cuenta' => '1101.02',
                'nombre_cuenta' => 'Créditos por Cobrar',
                'tipo' => 'activo',
                'naturaleza' => 'deudora',
                'nivel' => 3,
                'codigo_padre' => '1101',
                'acepta_movimientos' => false,
                'requiere_auxiliar' => false,
                'categoria_flujo' => 'operacion',
                'estado' => true,
            ],
            [
                'codigo_cuenta' => '1101.02.001',
                'nombre_cuenta' => 'Créditos Prendarios por Cobrar',
                'tipo' => 'activo',
                'naturaleza' => 'deudora',
                'nivel' => 4,
                'codigo_padre' => '1101.02',
                'acepta_movimientos' => true,
                'requiere_auxiliar' => true,
                'categoria_flujo' => 'operacion',
                'estado' => true,
            ],
            [
                'codigo_cuenta' => '1101.02.002',
                'nombre_cuenta' => 'Intereses por Cobrar',
                'tipo' => 'activo',
                'naturaleza' => 'deudora',
                'nivel' => 4,
                'codigo_padre' => '1101.02',
                'acepta_movimientos' => true,
                'requiere_auxiliar' => true,
                'categoria_flujo' => 'operacion',
                'estado' => true,
            ],
            [
                'codigo_cuenta' => '1101.02.003',
                'nombre_cuenta' => 'Mora por Cobrar',
                'tipo' => 'activo',
                'naturaleza' => 'deudora',
                'nivel' => 4,
                'codigo_padre' => '1101.02',
                'acepta_movimientos' => true,
                'requiere_auxiliar' => true,
                'categoria_flujo' => 'operacion',
                'estado' => true,
            ],
            [
                'codigo_cuenta' => '1101.02.004',
                'nombre_cuenta' => 'Estimación para Cuentas Incobrables',
                'tipo' => 'activo',
                'naturaleza' => 'acreedora',
                'nivel' => 4,
                'codigo_padre' => '1101.02',
                'acepta_movimientos' => true,
                'requiere_auxiliar' => false,
                'categoria_flujo' => 'ninguno',
                'estado' => true,
            ],

            // Inventario de Prendas
            [
                'codigo_cuenta' => '1101.03',
                'nombre_cuenta' => 'Inventario de Prendas',
                'tipo' => 'activo',
                'naturaleza' => 'deudora',
                'nivel' => 3,
                'codigo_padre' => '1101',
                'acepta_movimientos' => false,
                'requiere_auxiliar' => false,
                'categoria_flujo' => 'operacion',
                'estado' => true,
            ],
            [
                'codigo_cuenta' => '1101.03.001',
                'nombre_cuenta' => 'Prendas en Custodia (Avalúo)',
                'tipo' => 'activo',
                'naturaleza' => 'deudora',
                'nivel' => 4,
                'codigo_padre' => '1101.03',
                'acepta_movimientos' => true,
                'requiere_auxiliar' => false,
                'categoria_flujo' => 'operacion',
                'estado' => true,
            ],
            [
                'codigo_cuenta' => '1101.03.002',
                'nombre_cuenta' => 'Prendas para Venta',
                'tipo' => 'activo',
                'naturaleza' => 'deudora',
                'nivel' => 4,
                'codigo_padre' => '1101.03',
                'acepta_movimientos' => true,
                'requiere_auxiliar' => false,
                'categoria_flujo' => 'operacion',
                'estado' => true,
            ],
            [
                'codigo_cuenta' => '1101.03.003',
                'nombre_cuenta' => 'Deterioro de Inventario de Prendas',
                'tipo' => 'activo',
                'naturaleza' => 'acreedora',
                'nivel' => 4,
                'codigo_padre' => '1101.03',
                'acepta_movimientos' => true,
                'requiere_auxiliar' => false,
                'categoria_flujo' => 'ninguno',
                'estado' => true,
            ],

            // ==================== PASIVOS ====================
            [
                'codigo_cuenta' => '2',
                'nombre_cuenta' => 'PASIVO',
                'tipo' => 'pasivo',
                'naturaleza' => 'acreedora',
                'nivel' => 1,
                'codigo_padre' => null,
                'acepta_movimientos' => false,
                'requiere_auxiliar' => false,
                'categoria_flujo' => 'ninguno',
                'estado' => true,
            ],
            [
                'codigo_cuenta' => '2101',
                'nombre_cuenta' => 'PASIVO CORRIENTE',
                'tipo' => 'pasivo',
                'naturaleza' => 'acreedora',
                'nivel' => 2,
                'codigo_padre' => '2',
                'acepta_movimientos' => false,
                'requiere_auxiliar' => false,
                'categoria_flujo' => 'ninguno',
                'estado' => true,
            ],
            [
                'codigo_cuenta' => '2101.01',
                'nombre_cuenta' => 'Cuentas por Pagar',
                'tipo' => 'pasivo',
                'naturaleza' => 'acreedora',
                'nivel' => 3,
                'codigo_padre' => '2101',
                'acepta_movimientos' => false,
                'requiere_auxiliar' => false,
                'categoria_flujo' => 'operacion',
                'estado' => true,
            ],
            [
                'codigo_cuenta' => '2101.01.001',
                'nombre_cuenta' => 'Proveedores',
                'tipo' => 'pasivo',
                'naturaleza' => 'acreedora',
                'nivel' => 4,
                'codigo_padre' => '2101.01',
                'acepta_movimientos' => true,
                'requiere_auxiliar' => true,
                'categoria_flujo' => 'operacion',
                'estado' => true,
            ],
            [
                'codigo_cuenta' => '2101.02',
                'nombre_cuenta' => 'Impuestos por Pagar',
                'tipo' => 'pasivo',
                'naturaleza' => 'acreedora',
                'nivel' => 3,
                'codigo_padre' => '2101',
                'acepta_movimientos' => false,
                'requiere_auxiliar' => false,
                'categoria_flujo' => 'operacion',
                'estado' => true,
            ],
            [
                'codigo_cuenta' => '2101.02.001',
                'nombre_cuenta' => 'IVA por Pagar',
                'tipo' => 'pasivo',
                'naturaleza' => 'acreedora',
                'nivel' => 4,
                'codigo_padre' => '2101.02',
                'acepta_movimientos' => true,
                'requiere_auxiliar' => false,
                'categoria_flujo' => 'operacion',
                'estado' => true,
            ],
            [
                'codigo_cuenta' => '2101.02.002',
                'nombre_cuenta' => 'ISR por Pagar',
                'tipo' => 'pasivo',
                'naturaleza' => 'acreedora',
                'nivel' => 4,
                'codigo_padre' => '2101.02',
                'acepta_movimientos' => true,
                'requiere_auxiliar' => false,
                'categoria_flujo' => 'operacion',
                'estado' => true,
            ],

            // ==================== PATRIMONIO ====================
            [
                'codigo_cuenta' => '3',
                'nombre_cuenta' => 'PATRIMONIO',
                'tipo' => 'patrimonio',
                'naturaleza' => 'acreedora',
                'nivel' => 1,
                'codigo_padre' => null,
                'acepta_movimientos' => false,
                'requiere_auxiliar' => false,
                'categoria_flujo' => 'ninguno',
                'estado' => true,
            ],
            [
                'codigo_cuenta' => '3101',
                'nombre_cuenta' => 'Capital Social',
                'tipo' => 'patrimonio',
                'naturaleza' => 'acreedora',
                'nivel' => 2,
                'codigo_padre' => '3',
                'acepta_movimientos' => true,
                'requiere_auxiliar' => false,
                'categoria_flujo' => 'financiamiento',
                'estado' => true,
            ],
            [
                'codigo_cuenta' => '3102',
                'nombre_cuenta' => 'Resultados del Ejercicio',
                'tipo' => 'patrimonio',
                'naturaleza' => 'acreedora',
                'nivel' => 2,
                'codigo_padre' => '3',
                'acepta_movimientos' => true,
                'requiere_auxiliar' => false,
                'categoria_flujo' => 'ninguno',
                'estado' => true,
            ],
            [
                'codigo_cuenta' => '3103',
                'nombre_cuenta' => 'Resultados de Ejercicios Anteriores',
                'tipo' => 'patrimonio',
                'naturaleza' => 'acreedora',
                'nivel' => 2,
                'codigo_padre' => '3',
                'acepta_movimientos' => true,
                'requiere_auxiliar' => false,
                'categoria_flujo' => 'ninguno',
                'estado' => true,
            ],

            // ==================== INGRESOS ====================
            [
                'codigo_cuenta' => '4',
                'nombre_cuenta' => 'INGRESOS',
                'tipo' => 'ingreso',
                'naturaleza' => 'acreedora',
                'nivel' => 1,
                'codigo_padre' => null,
                'acepta_movimientos' => false,
                'requiere_auxiliar' => false,
                'categoria_flujo' => 'ninguno',
                'estado' => true,
            ],
            [
                'codigo_cuenta' => '4101',
                'nombre_cuenta' => 'INGRESOS OPERACIONALES',
                'tipo' => 'ingreso',
                'naturaleza' => 'acreedora',
                'nivel' => 2,
                'codigo_padre' => '4',
                'acepta_movimientos' => false,
                'requiere_auxiliar' => false,
                'categoria_flujo' => 'operacion',
                'estado' => true,
            ],
            [
                'codigo_cuenta' => '4101.01',
                'nombre_cuenta' => 'Intereses sobre Créditos Prendarios',
                'tipo' => 'ingreso',
                'naturaleza' => 'acreedora',
                'nivel' => 3,
                'codigo_padre' => '4101',
                'acepta_movimientos' => true,
                'requiere_auxiliar' => false,
                'categoria_flujo' => 'operacion',
                'estado' => true,
            ],
            [
                'codigo_cuenta' => '4101.02',
                'nombre_cuenta' => 'Mora sobre Créditos',
                'tipo' => 'ingreso',
                'naturaleza' => 'acreedora',
                'nivel' => 3,
                'codigo_padre' => '4101',
                'acepta_movimientos' => true,
                'requiere_auxiliar' => false,
                'categoria_flujo' => 'operacion',
                'estado' => true,
            ],
            [
                'codigo_cuenta' => '4101.03',
                'nombre_cuenta' => 'Comisiones por Servicios',
                'tipo' => 'ingreso',
                'naturaleza' => 'acreedora',
                'nivel' => 3,
                'codigo_padre' => '4101',
                'acepta_movimientos' => true,
                'requiere_auxiliar' => false,
                'categoria_flujo' => 'operacion',
                'estado' => true,
            ],
            [
                'codigo_cuenta' => '4101.04',
                'nombre_cuenta' => 'Venta de Prendas',
                'tipo' => 'ingreso',
                'naturaleza' => 'acreedora',
                'nivel' => 3,
                'codigo_padre' => '4101',
                'acepta_movimientos' => true,
                'requiere_auxiliar' => false,
                'categoria_flujo' => 'operacion',
                'estado' => true,
            ],

            // ==================== GASTOS ====================
            [
                'codigo_cuenta' => '5',
                'nombre_cuenta' => 'GASTOS',
                'tipo' => 'gasto',
                'naturaleza' => 'deudora',
                'nivel' => 1,
                'codigo_padre' => null,
                'acepta_movimientos' => false,
                'requiere_auxiliar' => false,
                'categoria_flujo' => 'ninguno',
                'estado' => true,
            ],
            [
                'codigo_cuenta' => '5101',
                'nombre_cuenta' => 'GASTOS OPERACIONALES',
                'tipo' => 'gasto',
                'naturaleza' => 'deudora',
                'nivel' => 2,
                'codigo_padre' => '5',
                'acepta_movimientos' => false,
                'requiere_auxiliar' => false,
                'categoria_flujo' => 'operacion',
                'estado' => true,
            ],
            [
                'codigo_cuenta' => '5101.01',
                'nombre_cuenta' => 'Sueldos y Salarios',
                'tipo' => 'gasto',
                'naturaleza' => 'deudora',
                'nivel' => 3,
                'codigo_padre' => '5101',
                'acepta_movimientos' => true,
                'requiere_auxiliar' => false,
                'categoria_flujo' => 'operacion',
                'estado' => true,
            ],
            [
                'codigo_cuenta' => '5101.02',
                'nombre_cuenta' => 'Alquileres',
                'tipo' => 'gasto',
                'naturaleza' => 'deudora',
                'nivel' => 3,
                'codigo_padre' => '5101',
                'acepta_movimientos' => true,
                'requiere_auxiliar' => false,
                'categoria_flujo' => 'operacion',
                'estado' => true,
            ],
            [
                'codigo_cuenta' => '5101.03',
                'nombre_cuenta' => 'Servicios Básicos',
                'tipo' => 'gasto',
                'naturaleza' => 'deudora',
                'nivel' => 3,
                'codigo_padre' => '5101',
                'acepta_movimientos' => true,
                'requiere_auxiliar' => false,
                'categoria_flujo' => 'operacion',
                'estado' => true,
            ],
            [
                'codigo_cuenta' => '5101.04',
                'nombre_cuenta' => 'Gastos de Seguridad y Custodia',
                'tipo' => 'gasto',
                'naturaleza' => 'deudora',
                'nivel' => 3,
                'codigo_padre' => '5101',
                'acepta_movimientos' => true,
                'requiere_auxiliar' => false,
                'categoria_flujo' => 'operacion',
                'estado' => true,
            ],
            [
                'codigo_cuenta' => '5102',
                'nombre_cuenta' => 'PROVISIONES Y ESTIMACIONES',
                'tipo' => 'gasto',
                'naturaleza' => 'deudora',
                'nivel' => 2,
                'codigo_padre' => '5',
                'acepta_movimientos' => false,
                'requiere_auxiliar' => false,
                'categoria_flujo' => 'operacion',
                'estado' => true,
            ],
            [
                'codigo_cuenta' => '5102.01',
                'nombre_cuenta' => 'Estimación para Cuentas Incobrables',
                'tipo' => 'gasto',
                'naturaleza' => 'deudora',
                'nivel' => 3,
                'codigo_padre' => '5102',
                'acepta_movimientos' => true,
                'requiere_auxiliar' => false,
                'categoria_flujo' => 'operacion',
                'estado' => true,
            ],
            [
                'codigo_cuenta' => '5102.02',
                'nombre_cuenta' => 'Deterioro de Inventario de Prendas',
                'tipo' => 'gasto',
                'naturaleza' => 'deudora',
                'nivel' => 3,
                'codigo_padre' => '5102',
                'acepta_movimientos' => true,
                'requiere_auxiliar' => false,
                'categoria_flujo' => 'operacion',
                'estado' => true,
            ],

            // ==================== COSTOS ====================
            [
                'codigo_cuenta' => '6',
                'nombre_cuenta' => 'COSTO DE VENTAS',
                'tipo' => 'costos',
                'naturaleza' => 'deudora',
                'nivel' => 1,
                'codigo_padre' => null,
                'acepta_movimientos' => false,
                'requiere_auxiliar' => false,
                'categoria_flujo' => 'ninguno',
                'estado' => true,
            ],
            [
                'codigo_cuenta' => '6101',
                'nombre_cuenta' => 'Costo de Prendas Vendidas',
                'tipo' => 'costos',
                'naturaleza' => 'deudora',
                'nivel' => 2,
                'codigo_padre' => '6',
                'acepta_movimientos' => true,
                'requiere_auxiliar' => false,
                'categoria_flujo' => 'operacion',
                'estado' => true,
            ],
        ];
    }
}
